### ISSUE TITLE
Extract runtime interop layer from node:* imports

### ISSUE THREAD

**Issue by mherod** [mherod/applescript-node#52]
## Parent Issue
Sub-issue of #48 (Add separate Node and Bun entry points)

## Business Context
The package currently hard-imports node:child_process, node:util, node:fs/promises, node:os, node:path, and node:crypto directly in 6 runtime-bound modules. This makes the package Node-only even though the builder/type surface is runtime-agnostic. Extracting these into an interop layer is the prerequisite for supporting alternative runtimes like Bun.

## Technical Context

**Runtime-bound modules and their node:* imports:**
- src/executor.ts:1-2 — node:child_process (exec), node:util (promisify)
- src/compiler.ts:1-6 — node:child_process, node:crypto, node:fs/promises, node:os, node:path, node:util
- src/decompiler.ts:1-2 — node:child_process, node:util
- src/languages.ts:1-2 — node:child_process, node:util
- src/loader.ts:1 — node:fs/promises
- src/sdef.ts:1-2 — node:child_process, node:util

**Runtime-agnostic modules (no changes needed):**
- src/builder.ts, src/types.ts, src/expressions.ts, src/validator.ts, src/sources/*

**Current build:** tsup.config.ts builds single entry src/index.ts. package.json exports single root entry.

## Scope of Work
1. Create src/runtime/interop.ts defining the runtime abstraction interface:
   - exec(command): Promise<{stdout, stderr}> — wraps child_process.exec
   - readFile(path, encoding): Promise<string> — wraps fs/promises.readFile
   - writeFile(path, data): Promise<void> — wraps fs/promises.writeFile
   - tmpdir(): string — wraps os.tmpdir
   - joinPath(...segments): string — wraps path.join
   - randomBytes(size): Buffer — wraps crypto.randomBytes
2. Create src/runtime/node.ts implementing the interface using node:* imports
3. Refactor all 6 runtime-bound modules to import from the interop layer instead of node:* directly
4. Default export still uses the Node adapter (no breaking changes)
5. All existing tests must continue to pass without modification

**NOT in scope:**
- Bun adapter implementation (sub-issue 2)
- Separate entry points / build config changes (sub-issue 2)
- Documentation updates (sub-issue 3)
- Test updates for new exports (sub-issue 3)

## Acceptance Criteria
- [ ] src/runtime/interop.ts defines a clean runtime abstraction interface
- [ ] src/runtime/node.ts implements the interface using Node.js APIs
- [ ] All 6 runtime-bound modules use the interop layer instead of direct node:* imports
- [ ] No node:* imports remain in non-runtime modules
- [ ] All existing tests pass (pnpm test)
- [ ] pnpm typecheck and pnpm lint pass
- [ ] No breaking changes to the public API

## Time Estimate
3-4 hours

## Dependencies
No blocking dependencies — this can be worked independently. Sub-issues 2 and 3 depend on this.
